packages:
  - .

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
  'dsh-annotation-core@https://codeload.github.com/linmu115/dsh-annotation-core/tar.gz/4bd5a042d403983e244c125f2f42512559d0e067': true
  esbuild: true
